#!/bin/sh /etc/rc.common
# Copyright (C) 2025
# Guangzhou College of Technology and Business portal login daemon

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/gzgspd --daemon --config /etc/gzgspd/config.json
    procd_set_param respawn 3600 30 3
    procd_set_param stdout 1
    procd_close_instance
}

stop_service() {
    # procd 会自动发送 SIGTERM，程序处理登出
    return 0
}
