name: Build

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
    branches: 
      - "main"
    tags: 
      - "v*.*.*"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.jobs.runs-on || 'ubuntu-latest' }}
    strategy:
      matrix:
        jobs:
          - { goos: darwin, goarch: amd64, goamd64: v1, output: amd64-compatible } # old style file name will be removed in next released
          - { goos: darwin, goarch: amd64, goamd64: v3, output: amd64 }
          - { goos: darwin, goarch: amd64, goamd64: v1, output: amd64-v1 }
          - { goos: darwin, goarch: amd64, goamd64: v2, output: amd64-v2 }
          - { goos: darwin, goarch: amd64, goamd64: v3, output: amd64-v3 }
          - { goos: darwin, goarch: arm64, output: arm64 }

          - { goos: linux, goarch: '386', go386: sse2, output: '386', debian: i386, rpm: i386 }
          - { goos: linux, goarch: '386', go386: softfloat, output: '386-softfloat' }
          - { goos: linux, goarch: amd64, goamd64: v1, output: amd64-compatible } # old style file name will be removed in next released
          - { goos: linux, goarch: amd64, goamd64: v3, output: amd64, debian: amd64, rpm: x86_64, pacman: x86_64 }
          - { goos: linux, goarch: amd64, goamd64: v1, output: amd64-v1, debian: amd64, rpm: x86_64, pacman: x86_64, test: test }
          - { goos: linux, goarch: amd64, goamd64: v2, output: amd64-v2, debian: amd64, rpm: x86_64, pacman: x86_64 }
          - { goos: linux, goarch: amd64, goamd64: v3, output: amd64-v3, debian: amd64, rpm: x86_64, pacman: x86_64 }
          - { goos: linux, goarch: arm64, output: arm64, debian: arm64, rpm: aarch64, pacman: aarch64 }  
          - { goos: linux, goarch: arm, goarm: '5', output: armv5 }
          - { goos: linux, goarch: arm, goarm: '6', output: armv6, debian: armel, rpm: armv6hl} 
          - { goos: linux, goarch: arm, goarm: '7', output: armv7, debian: armhf, rpm: armv7hl, pacman: armv7hl}
          - { goos: linux, goarch: mips, gomips: hardfloat, output: mips-hardfloat }
          - { goos: linux, goarch: mips, gomips: softfloat, output: mips-softfloat }
          - { goos: linux, goarch: mipsle, gomips: hardfloat, output: mipsle-hardfloat }
          - { goos: linux, goarch: mipsle, gomips: softfloat, output: mipsle-softfloat }
          - { goos: linux, goarch: mips64, output: mips64 }
          - { goos: linux, goarch: mips64le, output: mips64le, debian: mips64el, rpm: mips64el }
          - { goos: linux, goarch: loong64, output: loong64-abi1, abi: '1', debian: loongarch64, rpm: loongarch64 }
          - { goos: linux, goarch: loong64, output: loong64-abi2, abi: '2', debian: loong64, rpm: loong64 }
          - { goos: linux, goarch: riscv64, output: riscv64, debian: riscv64, rpm: riscv64 }
          - { goos: linux, goarch: s390x, output: s390x, debian: s390x, rpm: s390x }
          - { goos: linux, goarch: ppc64le, output: ppc64le, debian: ppc64el, rpm: ppc64le }

          - { goos: windows, goarch: '386', output: '386', gui: true }
          - { goos: windows, goarch: amd64, goamd64: v1, output: amd64-compatible, gui: true } # old style file name will be removed in next released
          - { goos: windows, goarch: amd64, goamd64: v3, output: amd64, gui: true }
          - { goos: windows, goarch: amd64, goamd64: v1, output: amd64-v1, gui: true }
          - { goos: windows, goarch: amd64, goamd64: v2, output: amd64-v2, gui: true }
          - { goos: windows, goarch: amd64, goamd64: v3, output: amd64-v3, gui: true }
          - { goos: windows, goarch: arm64, output: arm64, gui: true }

          - { goos: freebsd, goarch: '386', output: '386' }
          - { goos: freebsd, goarch: amd64, goamd64: v1, output: amd64-compatible } # old style file name will be removed in next released
          - { goos: freebsd, goarch: amd64, goamd64: v3, output: amd64 }
          - { goos: freebsd, goarch: amd64, goamd64: v1, output: amd64-v1 }
          - { goos: freebsd, goarch: amd64, goamd64: v2, output: amd64-v2 }
          - { goos: freebsd, goarch: amd64, goamd64: v3, output: amd64-v3 }
          - { goos: freebsd, goarch: arm64, output: arm64 }

          - { goos: android, goarch: '386', ndk: i686-linux-android34, output: '386' }
          - { goos: android, goarch: amd64, ndk: x86_64-linux-android34, output: amd64 }
          - { goos: android, goarch: arm, ndk: armv7a-linux-androideabi34, output: armv7 }
          - { goos: android, goarch: arm64, ndk: aarch64-linux-android34, output: arm64-v8 }

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Install linux dependencies
        if: ${{ matrix.jobs.goos == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgtk-3-dev libayatana-appindicator3-dev

      - name: Set up environment variables
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME,,}-$(git rev-parse --short HEAD)"
          VERSION="${VERSION//\//-}"
          PackageVersion=${GITHUB_RUN_ID}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "PackageVersion=${PackageVersion}" >> $GITHUB_ENV

          echo "BUILDTIME=$(date)" >> $GITHUB_ENV
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
          echo "BUILDTAG=-extldflags --static" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

      - name: Set up environment in windows
        if: ${{ matrix.jobs.goos == 'windows' }}
        shell: bash
        run: |
          echo "BUILDTAG=${BUILDTAG} -H windowsgui" >> $GITHUB_ENV
          go install github.com/akavel/rsrc@latest
          $(go env GOPATH)/bin/rsrc.exe -ico src/assets/logo.ico -o src/rsrc.syso

      - name: Setup NDK
        if: ${{ matrix.jobs.goos == 'android' }}
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d

      - name: Set NDK path
        if: ${{ matrix.jobs.goos == 'android' }}
        run: |
          echo "CC=${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{matrix.jobs.ndk}}-clang" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "BUILDTAG=" >> $GITHUB_ENV

      - name: Build core
        env:
          GOOS: ${{matrix.jobs.goos}}
          GOARCH: ${{matrix.jobs.goarch}}
          GOAMD64: ${{matrix.jobs.goamd64}}
          GO386: ${{matrix.jobs.go386}}
          GOARM: ${{matrix.jobs.goarm}}
          GOMIPS: ${{matrix.jobs.gomips}}
        run: |
          cd src
          go env
          go build -v -trimpath -ldflags "${BUILDTAG} -X 'main.Version=${VERSION}' -w -s" -o ../gzgspd
          cd ..
          if [ "${{matrix.jobs.goos}}" = "windows" ]; then
            cp gzgspd gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
            zip -r gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.zip gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
          else
            cp gzgspd gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
            gzip -c gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}} > gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.gz
            rm gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
          fi

      - name: Build gui
        if: matrix.jobs.gui == true
        env:
          GOOS: ${{matrix.jobs.goos}}
          GOARCH: ${{matrix.jobs.goarch}}
          GOAMD64: ${{matrix.jobs.goamd64}}
          GO386: ${{matrix.jobs.go386}}
          GOARM: ${{matrix.jobs.goarm}}
          GOMIPS: ${{matrix.jobs.gomips}}
        run: |
          export CGO_ENABLED=1
          cd src
          go env
          go build -v -tags gui -trimpath -ldflags "${BUILDTAG} -X 'main.Version=${VERSION}' -w -s" -o ../gzgspd-gui
          cd ..
          if [ "${{matrix.jobs.goos}}" = "windows" ]; then
            cp gzgspd-gui gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
            zip -r gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.zip gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
          else
            cp gzgspd-gui gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
            gzip -c gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}} > gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.gz
            rm gzgspd-gui-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
          fi

      - name: Package DEB
        if: matrix.jobs.debian != ''
        run: |
          set -xeuo pipefail
          sudo gem install fpm
          cp files/release/.fpm .fpm

          fpm -t deb \
            -v "${PackageVersion}" \
            -p "gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.deb" \
            --architecture ${{ matrix.jobs.debian }} \
            gzgspd=/usr/bin/gzgspd

      - name: Package RPM
        if: matrix.jobs.rpm != ''
        run: |
          set -xeuo pipefail
          sudo gem install fpm
          cp files/release/.fpm .fpm

          fpm -t rpm \
            -v "${PackageVersion}" \
            -p "gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.rpm" \
            --architecture ${{ matrix.jobs.rpm }} \
            gzgspd=/usr/bin/gzgspd

      - name: Package Pacman
        if: matrix.jobs.pacman != ''
        run: |
          set -xeuo pipefail
          sudo gem install fpm
          sudo apt-get update && sudo apt-get install -y libarchive-tools
          cp files/release/.fpm .fpm

          fpm -t pacman \
            -v "${PackageVersion}" \
            -p "gzgspd-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.pkg.tar.zst" \
            --architecture ${{ matrix.jobs.pacman }} \
            gzgspd=/usr/bin/gzgspd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.jobs.goos }}-${{ matrix.jobs.output }}"
          path: |
            gzgspd*.gz
            gzgspd*.deb
            gzgspd*.rpm
            gzgspd*.pkg.tar.zst
            gzgspd*.zip
            version.txt
            checksums.txt

  release:
    # 只在 tag push 时执行
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        with:
          name: Release ${{ github.ref_name }}
          files: bin/*
          draft: true
          generate_release_notes: true
